<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<!--async/await와 try/catch를 활용해 외부 API에서 사용자 정보를 불러오는 기능을 수행-->
<body>
    <h2>사용자 정보 가져오기</h2>
    <button onclick="loadUser()">사용자 정보 불러오기</button>

    <pre id="result"></pre>

    <script>
        async function loadUser() { // async: 비동기 함수 선언. 내부에서 await 사용 가능

            try { // 오류가 발생할 수 있는 구간을 감싸는 try 구문
            const response = await fetch("https://jsonplaceholder.typicode.com/users/2");
            // ↑ fetch() 함수를 사용해 외부 API에 요청을 보냄. / await를 사용하여 요청이 끝날 때까지 기다림.
            console.log(response); // 받은 응답 객체(Response)를 콘솔에 출력.
            
            if(!response.ok) { // 응답 상태 코드가 200번대가 아닐 경우 예외를 발생시킴.
                throw new Error(`Http 오류 : ${response.status}`);
            }
            const data = await response.json(); // 응답 본문을 JSON 데이터로 파싱.
            console.log(data);

            document.getElementById("result").textContent = JSON.stringify(data, null, 2);
        } catch(error) {
            console.error("데이터 가져오는 중 오류 발생: " + error);
        }
    }
    </script>
</body>
</html>